repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      name: Running Black Formatter
      language_version: python3.9
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    # Use args to ignore errors related to Black formatting
    # args: ["--ignore", "E203,E266,E501,W503,F401,F403"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      name: Running flake8 formatter
