# https://pdm.fming.dev/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile
# https://fastapi.tiangolo.com/deployment/docker/#build-a-docker-image-with-a-single-file-fastapi

# build stage
FROM python:3.9-slim AS builder

# install PDM
RUN pip install -U pip setuptools wheel
RUN pip install pdm

# copy PDM files to project
COPY pyproject.toml pdm.lock README.md /project/

# install dependencies and project
WORKDIR /project
RUN pdm install --prod --no-lock --no-editable

# run stage
FROM python:3.9-slim

# retrieve packages from build stage
ENV PYTHONPATH=/project/pkgs
COPY --from=builder /project/__pypackages__/3.9/lib /project/pkgs

# copy project files
COPY ./main.py /project/

# Use entrypoint to keep Docker container running for debugging
# ENTRYPOINT ["tail", "-f", "/dev/null"]

# set command/entrypoint, adapt to fit your needs
CMD ["python", "-m", "uvicorn", "project.main:app", "--host", "0.0.0.0", "--port", "80"]

EXPOSE 8000
