# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipenv-example02-image
    container_name: pipenv-example02-container
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 80:8000
    networks:
      - hello_world_network

networks:
  hello_world_network:
    driver: bridge
