# https://jonathanmeier.io/using-pipenv-with-docker/
FROM python:3.9-slim

# set environment variables
# PYTHONDONTWRITEBYTECODE: Prevents Python from writing pyc files to disc (equivalent to python -B option)
# PYTHONUNBUFFERED: Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install pipenv

WORKDIR /project

COPY Pipfile Pipfile.lock /project/

RUN pipenv install --system --deploy

# copy project files
COPY ./main.py /project/

EXPOSE 8000
