# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipenv-example02-image
    container_name: pipenv-example02-container
    command: python -m uvicorn project.main:app --host 0.0.0.0 --port 8000
    environment:
      - PACKAGE_MANAGER_NAME=Pipenv
    ports:
      - 80:8000
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
