# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipenv-example05-image
    container_name: pipenv-example05-container
    command: python -m main
    environment:
      - PACKAGE_MANAGER_NAME=Pipenv
    ports:
      - 80:8000
    networks:
      - fastapiusers

networks:
  fastapiusers:
    driver: bridge
