# https://jonathanmeier.io/using-pipenv-with-docker/
FROM python:3.9-slim

ENV PYTHONPATH=/project/pkgs
# ENV PACKAGE_MANAGER_NAME=Pipenv

RUN pip install pipenv

WORKDIR /project

COPY Pipfile Pipfile.lock /project/

RUN pipenv install --system --deploy

COPY ./src /project/src

EXPOSE 8000
