# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdm-example10-image
    container_name: pdm-example10-container
    command: python -m main
    environment:
      - PACKAGE_MANAGER_NAME=PDM
      # https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.asyncpg
      - DATABASE_URL=postgresql+asyncpg://example10:passw0rd@db/example10
    ports:
      - 80:8000
    depends_on:
      - db

  # https://fastapi-tutorial.readthedocs.io/en/latest/#postgres-setup
  db:
    image: postgres:13.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=example10
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=example10

volumes:
  postgres_data:
