# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-compose-oauth2-bearer-fake-db
    command: python -m main
    ports:
      - 80:8000
    networks:
      - fastapiusers

networks:
  fastapiusers:
    driver: bridge
