# https://towardsdev.com/dockerize-your-apis-fastapi-part1-f44302652af9
# https://fastapi-tutorial.readthedocs.io/en/latest/#project-setup
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: docker-compose-fastapi-users-jwt-bearer-db-cookie
    command: python -m main
    ports:
      - 80:8000
    networks:
      - fastapiusers

networks:
  fastapiusers:
    driver: bridge
